### ISSUE TITLE
After configuring everything, run Python \Launch. py frames=-1 view=true quit=q d=2.5 lr=1.5,1.5 ud=1,1, RealSense2OpenPose3D.exe application failed to start properly

### ISSUE THREAD

**Issue by kekekou** [foxtierney/RealSense2OpenPose3D#5]
As shown in the following figure, what is the reason for this? Thank you in advance for answering my questions @xiangyann 

![875c9675339b6cd3464b787795cc4ce](https://github.com/foxtierney/RealSense2OpenPose3D/assets/138195937/507caf68-5567-433c-8aa3-e8ddb028da8a)

**Comment by xiangyann** [comment]
Is OpenPose correctly configured to run? The process doesn't seem to launch correctly.

**Comment by kekekou** [comment]
@xiangyann @foxtierney  I have configured openpose to run smoothly. The following example can detect key points, but I cannot run build/x64/Release/OpenPoseDemo.exe -- hand -- face -- camera 1

I don't know where the problem is
![c260b3a061b0a91611293c174f49f7d](https://github.com/foxtierney/RealSense2OpenPose3D/assets/138195937/898bb9c4-e01e-4c5e-a016-ac7348fc81c6)

**Comment by xiangyann** [comment]
> @xiangyann @foxtierney I have configured openpose to run smoothly. The following example can detect key points, but I cannot run build/x64/Release/OpenPoseDemo.exe -- hand -- face -- camera 1
> 
> I don't know where the problem is ![c260b3a061b0a91611293c174f49f7d](https://user-images.githubusercontent.com/138195937/280207199-898bb9c4-e01e-4c5e-a016-ac7348fc81c6.png)

You need to edit the launch.py file to suit your path

**Comment by kekekou** [comment]
> > @xiangyann @foxtierney我已经配置了 openpose 可以顺利运行。下面的例子可以检测到关键点，但是我无法运行build/x64/Release/OpenPoseDemo.exe -- hand --face --camera 1
> > 我不知道问题出在哪里![c260b3a061b0a91611293c174f49f7d](https://user-images.githubusercontent.com/138195937/280207199-898bb9c4-e01e-4c5e-a016-ac7348fc81c6.png)
> 
> 您需要编辑 launch.py​​ 文件以适合您的路径
I have already modified the path to the launch.py file

**Comment by kekekou** [comment]
Also, I have another question. Can RealSense2OpenPose3D be placed in the openpose path? Can this depth camera also recognize 3D key points of hands other than the body?I don't know why two realsense cameras cannot recognize the 3D key points of the hand when using Openpose.Thank you in advance for your answer. Thank you very much!! @xiangyann

**Comment by foxtierney** [comment]
> @xiangyann @foxtierney I have configured openpose to run smoothly. The following example can detect key points, but I cannot run build/x64/Release/OpenPoseDemo.exe -- hand -- face -- camera 1
> 
> I don't know where the problem is ![c260b3a061b0a91611293c174f49f7d](https://user-images.githubusercontent.com/138195937/280207199-898bb9c4-e01e-4c5e-a016-ac7348fc81c6.png)

One thing I wonder, is `build/x64/Release/OpenPoseDemo.exe -- hand -- face -- camera 1` the exact command you are using? I find that if I run that, I do not get the face and hands to work. Try removing the spaces so that the command looks like this instead: `./build/x64/Release/OpenPoseDemo.exe --hand --face --camera 1`


> Can RealSense2OpenPose3D be placed in the openpose path? 

I think that RealSense2OpenPose3D.exe can be placed anywhere as long as the path is configured in the launch.py file.


> Can this depth camera also recognize 3D key points of hands other than the body?

It should be able to work with hands too, thanks to the additions recently made by @xiangyann.

**Comment by foxtierney** [comment]
> As shown in the following figure, what is the reason for this? Thank you in advance for answering my questions @xiangyann
> 
> ![875c9675339b6cd3464b787795cc4ce](https://user-images.githubusercontent.com/138195937/279965032-507caf68-5567-433c-8aa3-e8ddb028da8a.png)

As for your initial issue, what is that 'q' at the very end of your command? Is that you pressing the 'q' key or was it entered into the command? RS2OP3D is not too robust to unknown input. So if it tries to read `"ud=1,1q"` as two numbers separated by the ',' then there will be an error when "1q" is attempted to be converted to a float.

**Comment by xiangyann** [comment]
> Also, I have another question. Can RealSense2OpenPose3D be placed in the openpose path? Can this depth camera also recognize 3D key points of hands other than the body?I don't know why two realsense cameras cannot recognize the 3D key points of the hand when using Openpose.Thank you in advance for your answer. Thank you very much!! @xiangyann

You mentioned about "two realsense cameras", what does it mean? Did you meant the array on a camera, or you are using two physical realsense cameras? Hands are already available since the last patch.
CN translate: 你說到用你用了兩台 realsense 相機，是指一台realsense本身的相機陣列，還是指兩台不同的的實體相機？手部偵測在現行階段已經是可以使用的。

**Comment by kekekou** [comment]
> > 另外，我还有另一个问题。RealSense2OpenPose3D 可以放置在 openpose 路径中吗？这款深度相机还能识别身体以外的手部的 3D 关键点吗？不知道为什么两个实感摄像头在使用Openpose时都无法识别手部的3D关键点。谢谢！！
> 
> 你提到“两个实感相机”，这是什么意思？您指的是摄像机上的阵列，还是您使用的是两个物理实感摄像机？自上一个补丁以来，手牌已经可用。 CN translate： 你說到用你用了兩台 realsense 相機，是指一台realsense本身的相機陣列，還是指兩台不同的實體相機？手部偵測在現行階段已經是可以使用的。

Thanks for the reply, when I say with two realsense cameras, I mean two different physical cameras.I guess the reason for the above problem is because I didn't compile and generate RealSense2OpenPose3D .exe. After compiling and generating realsense2OpenPose3D .exe, I got the following.In the output data, keypoints.json has data. And keypointsD.json opens up as {
    "people": [],
    "version": 1.3
}

![屏幕截图(3)](https://github.com/foxtierney/RealSense2OpenPose3D/assets/138195937/0759265f-cf14-47d1-a399-2e90e99c5d82)

**Comment by kekekou** [comment]
> > @xiangyann @foxtierney I have configured openpose to run smoothly. The following example can detect key points, but I cannot run build/x64/Release/OpenPoseDemo.exe -- hand -- face -- camera 1
> > I don't know where the problem is ![c260b3a061b0a91611293c174f49f7d](https://user-images.githubusercontent.com/138195937/280207199-898bb9c4-e01e-4c5e-a016-ac7348fc81c6.png)
> 
> One thing I wonder, is the exact command you are using? I find that if I run that, I do not get the face and hands to work. Try removing the spaces so that the command looks like this instead: `build/x64/Release/OpenPoseDemo.exe -- hand -- face -- camera 1``./build/x64/Release/OpenPoseDemo.exe --hand --face --camera 1`
> 
> > Can RealSense2OpenPose3D be placed in the openpose path?
> 
> I think that RealSense2OpenPose3D.exe can be placed anywhere as long as the path is configured in the launch.py file.
> 
> > Can this depth camera also recognize 3D key points of hands other than the body?
> 
> It should be able to work with hands too, thanks to the additions recently made by @xiangyann.

Yes, you are right. I can successfully call up the camera.Thank you very much！

**Comment by kekekou** [comment]
> > As shown in the following figure, what is the reason for this? Thank you in advance for answering my questions @xiangyann
> > ![875c9675339b6cd3464b787795cc4ce](https://user-images.githubusercontent.com/138195937/279965032-507caf68-5567-433c-8aa3-e8ddb028da8a.png)
> 
> As for your initial issue, what is that 'q' at the very end of your command? Is that you pressing the 'q' key or was it entered into the command? RS2OP3D is not too robust to unknown input. So if it tries to read as two numbers separated by the ',' then there will be an error when "1q" is attempted to be converted to a float.`"ud=1,1q"`

This happens because I want to stop the program after pressing Q.

**Comment by kekekou** [comment]
I'm really sorry, I also ran the 3D reconstruction of openpose, the question is that the final output result is as shown in the figure below, can you answer it?
![2023-11-14 11-03-31 的屏幕截图](https://github.com/foxtierney/RealSense2OpenPose3D/assets/138195937/c0b2e937-ee72-4f9e-bbac-b012a44df078)

**Comment by foxtierney** [comment]
> And keypointsD.json opens up as {
>"people": [],
>"version": 1.3
>}

This is because there are no people in the scene. Only frames with people will have any people in the "people" array.

>This happens because I want to stop the program after pressing Q.

Does this still happen or has it been resolved now that you compiled RS2OP3D.exe yourself?

> I'm really sorry, I also ran the 3D reconstruction of openpose, the question is that the final output result is as shown in the figure below, can you answer it?

As far as I can tell, this output is the normal output from OpenPose. If RS2OP3D modified the file, it should be formatted nicely instead of mixed up like the raw OpenPose json files are. Like this: 
![image](https://github.com/foxtierney/RealSense2OpenPose3D/assets/116548090/79f19529-0400-497a-824a-4b4beb148562)
![image](https://github.com/foxtierney/RealSense2OpenPose3D/assets/116548090/d18cd8df-b95f-4034-96d2-ab0cdd613cdd)

**Comment by kekekou** [comment]
> > And keypointsD.json opens up as {
> > "people": [],
> > "version": 1.3
> > }
> 
> This is because there are no people in the scene. Only frames with people will have any people in the "people" array.
>  I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
{
"people": [],
"version": 1.3
}"
> > This happens because I want to stop the program after pressing Q.
> 
> Does this still happen or has it been resolved now that you compiled RS2OP3D.exe yourself?
> I have already resolved this issue.
> > I'm really sorry, I also ran the 3D reconstruction of openpose, the question is that the final output result is as shown in the figure below, can you answer it?
> 
> As far as I can tell, this output is the normal output from OpenPose. If RS2OP3D modified the file, it should be formatted nicely instead of mixed up like the raw OpenPose json files are. Like this: ![image](https://user-images.githubusercontent.com/116548090/283312518-79f19529-0400-497a-824a-4b4beb148562.png) ![image](https://user-images.githubusercontent.com/116548090/283312565-d18cd8df-b95f-4034-96d2-ab0cdd613cdd.png)
>"I'm sorry for not expressing myself clearly. I want to ask about the output files generated when I perform separate 3D reconstruction using OpenPose. The generated files display 3D positions, but I'm unsure why 3D hand positions are not appearing."

**Comment by kekekou** [comment]
> > keypointsD.json 打开为 { 
> > "people": [], 
> > "version": 1.3 
> > }
> 这是因为现场没有人。只有包含人物的帧才会在“people”数组中包含任何人。
>  I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
{
"people": [],
"version": 1.3
}"

> 

> > 发生这种情况是因为我想在按 Q 后停止程序。
> 
> 现在您自己编译了RS2OP3D.exe，这种情况是否仍然发生或者已经解决？
> I have already resolved this 

> issue.

> > 实在抱歉，我也跑了openpose的3D重建，问题是最终输出结果如下图所示，你能回答一下吗？
> 
> 据我所知，这个输出是 OpenPose 的正常输出。如果 RS2OP3D 修改了文件，它应该被很好地格式化，而不是像原始 OpenPose json 文件那样混合在一起。像这样： ![图像](https://user-images.githubusercontent.com/116548090/283312518-79f19529-0400-497a-824a-4b4beb148562.png) ![图像](https://user-images.githubusercontent.com/116548090/283312565-d18cd8df-b95f-4034-96d2-ab0cdd613cdd.png)

**Comment by kekekou** [comment]
> This is because there are no people in the scene. Only frames with people will have any people in the "people" array.

 I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
{
"people": [],
"version": 1.3
}"

> Does this still happen or has it been resolved now that you compiled RS2OP3D.exe yourself?

I have already resolved this issue.

> As far as I can tell, this output is the normal output from OpenPose. If RS2OP3D modified the file, it should be formatted nicely instead of mixed up like the raw OpenPose json files are. Like this:

I'm sorry for not expressing myself clearly. I want to ask about the output files generated when I perform separate 3D reconstruction using OpenPose. The generated files display 3D positions, but I'm unsure why 3D hand positions are not appearing.
![2023-11-14 11-03-31 的屏幕截图](https://github.com/foxtierney/RealSense2OpenPose3D/assets/138195937/4503ddbd-6a68-41fc-9921-b4296147db27)

**Comment by kekekou** [comment]
As a beginner, I have been experimenting with both OpenPose 3D reconstruction and RealSense2OpenPose3D. I am currently facing a major issue with the OpenPose 3D reconstruction, as it is unable to detect the hand pose (I am using two physical RealSense cameras for this experiment). In another experiment, RealSense2OpenPose3D, I have encountered the problem I described in my previous response.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月16日(星期四) 中午11:32
收件人: "foxtierney/RealSense2OpenPose3D";
抄送: "Author";
主题: Re: [foxtierney/RealSense2OpenPose3D] After configuring everything, run Python \Launch. py frames=-1 view=true quit=q d=2.5 lr=1.5,1.5 ud=1,1, RealSense2OpenPose3D.exe application failed to start properly (Issue #5)





  
And keypointsD.json opens up as {
 "people": [],
 "version": 1.3
 }
  
This is because there are no people in the scene. Only frames with people will have any people in the "people" array.
  
This happens because I want to stop the program after pressing Q.
  
Does this still happen or has it been resolved now that you compiled RS2OP3D.exe yourself?
  
I'm really sorry, I also ran the 3D reconstruction of openpose, the question is that the final output result is as shown in the figure below, can you answer it?
  
As far as I can tell, this output is the normal output from OpenPose. If RS2OP3D modified the file, it should be formatted nicely instead of mixed up like the raw OpenPose json files are. Like this:
 
 
 
&mdash;

**Comment by foxtierney** [comment]
> I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
{
"people": [],
"version": 1.3
}"

Just to confirm, keypoints.json files have people detected in them but the keypointsD.json files appear as above, with no people? Are there the same number of keypoint files for both the normal and the D versions? So, say you ran the program for 101 frames, would you have up to 0...0100_keypoints.json and also 0...0100keypointsD.json?

Would you mind testing with all combinations of the --hand --face flags? I am wondering if there is some issue in the logic that determines what should be injected into the new, depth, file. Thank you.

> As a beginner, I have been experimenting with both OpenPose 3D reconstruction and RealSense2OpenPose3D. I am currently facing a major issue with the OpenPose 3D reconstruction, as it is unable to detect the hand pose (I am using two physical RealSense cameras for this experiment).

It seems like the built-in 3D reconstruction in OpenPose only works, or at least is made for FLIR brand cameras, not all depth cameras (like the RealSense cameras you are using). See [OpenPose's documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/advanced/3d_reconstruction_module.md#required-hardware). I may be wrong though.

**Comment by xiangyann** [comment]
> > I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
> > {
> > "people": [],
> > "version": 1.3
> > }"
> 
> Just to confirm, keypoints.json files have people detected in them but the keypointsD.json files appear as above, with no people? Are there the same number of keypoint files for both the normal and the D versions? So, say you ran the program for 101 frames, would you have up to 0...0100_keypoints.json and also 0...0100keypointsD.json?
> 
> Would you mind testing with all combinations of the --hand --face flags? I am wondering if there is some issue in the logic that determines what should be injected into the new, depth file. Thank you.
> 
> > As a beginner, I have been experimenting with both OpenPose 3D reconstruction and RealSense2OpenPose3D. I am currently facing a major issue with the OpenPose 3D reconstruction, as it is unable to detect the hand pose (I am using two physical RealSense cameras for this experiment).
> 
> It seems like the built-in 3D reconstruction in OpenPose only works, or at least is made for FLIR brand cameras, not all depth cameras (like the RealSense cameras you are using). See [OpenPose's documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/advanced/3d_reconstruction_module.md#required-hardware). I may be wrong though.

I have FLIR cameras, couldn't get 3d pose to work since 3 years ago. (You can see my recent attempts at the PR in openpose repo)

Which is why I stumbled upon this project in the first place 😂

**Comment by kekekou** [comment]
> > I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
> > {
> > "people": [],
> > "version": 1.3
> > }"
> 
> Just to confirm, keypoints.json files have people detected in them but the keypointsD.json files appear as above, with no people? Are there the same number of keypoint files for both the normal and the D versions? So, say you ran the program for 101 frames, would you have up to 0...0100_keypoints.json and also 0...0100keypointsD.json?
> 
> Would you mind testing with all combinations of the --hand --face flags? I am wondering if there is some issue in the logic that determines what should be injected into the new, depth, file. Thank you.
> 
> > As a beginner, I have been experimenting with both OpenPose 3D reconstruction and RealSense2OpenPose3D. I am currently facing a major issue with the OpenPose 3D reconstruction, as it is unable to detect the hand pose (I am using two physical RealSense cameras for this experiment).
> 
> It seems like the built-in 3D reconstruction in OpenPose only works, or at least is made for FLIR brand cameras, not all depth cameras (like the RealSense cameras you are using). See [OpenPose's documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/advanced/3d_reconstruction_module.md#required-hardware). I may be wrong though.

I apologize for not replying for so long. Yes, the keypoints file detected a person, but there were no people detected in the keypointsD file. The number of individuals in the two files may differ, and the RealSense2OpenPose3D.exe program will suddenly terminate. I would like to know where to add the hand and face detections. I'm sorry, but is it something I need to add while compiling RealSense2OpenPose3D.exe?

**Comment by kekekou** [comment]
> > > I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
> > > {
> > > "people": [],
> > > "version": 1.3
> > > }"
> > 
> > 
> > Just to confirm, keypoints.json files have people detected in them but the keypointsD.json files appear as above, with no people? Are there the same number of keypoint files for both the normal and the D versions? So, say you ran the program for 101 frames, would you have up to 0...0100_keypoints.json and also 0...0100keypointsD.json?
> > Would you mind testing with all combinations of the --hand --face flags? I am wondering if there is some issue in the logic that determines what should be injected into the new, depth, file. Thank you.
> > > As a beginner, I have been experimenting with both OpenPose 3D reconstruction and RealSense2OpenPose3D. I am currently facing a major issue with the OpenPose 3D reconstruction, as it is unable to detect the hand pose (I am using two physical RealSense cameras for this experiment).
> > 
> > 
> > It seems like the built-in 3D reconstruction in OpenPose only works, or at least is made for FLIR brand cameras, not all depth cameras (like the RealSense cameras you are using). See [OpenPose's documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/advanced/3d_reconstruction_module.md#required-hardware). I may be wrong though.
> 
> I apologize for not replying for so long. Yes, the keypoints file detected a person, but there were no people detected in the keypointsD file. The number of individuals in the two files may differ, and the RealSense2OpenPose3D.exe program will suddenly terminate. I would like to know where to add the hand and face detections. I'm sorry, but is it something I need to add while compiling RealSense2OpenPose3D.exe?

Sure, I will go and take a look. Thank you for reminding me.

**Comment by kekekou** [comment]
> > > I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
> > > {
> > > "people": [],
> > > "version": 1.3
> > > }"
> > 
> > 
> > Just to confirm, keypoints.json files have people detected in them but the keypointsD.json files appear as above, with no people? Are there the same number of keypoint files for both the normal and the D versions? So, say you ran the program for 101 frames, would you have up to 0...0100_keypoints.json and also 0...0100keypointsD.json?
> > Would you mind testing with all combinations of the --hand --face flags? I am wondering if there is some issue in the logic that determines what should be injected into the new, depth file. Thank you.
> > > As a beginner, I have been experimenting with both OpenPose 3D reconstruction and RealSense2OpenPose3D. I am currently facing a major issue with the OpenPose 3D reconstruction, as it is unable to detect the hand pose (I am using two physical RealSense cameras for this experiment).
> > 
> > 
> > It seems like the built-in 3D reconstruction in OpenPose only works, or at least is made for FLIR brand cameras, not all depth cameras (like the RealSense cameras you are using). See [OpenPose's documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/advanced/3d_reconstruction_module.md#required-hardware). I may be wrong though.
> 
> I have FLIR cameras, couldn't get 3d pose to work since 3 years ago. (You can see my recent attempts at the PR in openpose repo)
> 
> Which is why I stumbled upon this project in the first place 😂

Sure, I will go and take a look. Thank you for reminding me.

**Comment by xiangyann** [comment]
> > > I have checked all the 'keypointsD.json' files, but there is no data present. When I open the files, I see the following content:
> > > {
> > > "people": [],
> > > "version": 1.3
> > > }"
> > 
> > 
> > Just to confirm, keypoints.json files have people detected in them but the keypointsD.json files appear as above, with no people? Are there the same number of keypoint files for both the normal and the D versions? So, say you ran the program for 101 frames, would you have up to 0...0100_keypoints.json and also 0...0100keypointsD.json?
> > Would you mind testing with all combinations of the --hand --face flags? I am wondering if there is some issue in the logic that determines what should be injected into the new, depth, file. Thank you.
> > > As a beginner, I have been experimenting with both OpenPose 3D reconstruction and RealSense2OpenPose3D. I am currently facing a major issue with the OpenPose 3D reconstruction, as it is unable to detect the hand pose (I am using two physical RealSense cameras for this experiment).
> > 
> > 
> > It seems like the built-in 3D reconstruction in OpenPose only works, or at least is made for FLIR brand cameras, not all depth cameras (like the RealSense cameras you are using). See [OpenPose's documentation](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/advanced/3d_reconstruction_module.md#required-hardware). I may be wrong though.
> 
> I apologize for not replying for so long. Yes, the keypoints file detected a person, but there were no people detected in the keypointsD file. The number of individuals in the two files may differ, and the RealSense2OpenPose3D.exe program will suddenly terminate. I would like to know where to add the hand and face detections. I'm sorry, but is it something I need to add while compiling RealSense2OpenPose3D.exe?

@foxtierney I don't think we'd ever updated the Release build, so it shouldn't be having a build with hand detection...

As for @kekekou you can build the file yourself in the meantime

**Comment by foxtierney** [comment]
> @foxtierney I don't think we'd ever updated the Release build, so it shouldn't be having a build with hand detection...

That's true... The built version has not yet been updated... Good catch! I just did that.

@kekekou I have just rebuilt the project (and realized that there were .dlls that needed to be included) Please download the [latest release](https://github.com/foxtierney/RealSense2OpenPose3D/releases/tag/1.1) folder and try again. Thank you for your patience.

**Comment by kekekou** [comment]
> 

> > @foxtierney I don't think we'd ever updated the Release build, so it shouldn't be having a build with hand detection...
> 
> That's true... The built version has not yet been updated... Good catch! I just did that.
> 
> @kekekou I have just rebuilt the project (and realized that there were .dlls that needed to be included) Please download the [latest release](https://github.com/foxtierney/RealSense2OpenPose3D/releases/tag/1.1) folder and try again. Thank you for your patience.

> Sorry for the inconvenience. I've been busy with my coursework recently, but after downloading the new release, I was able to succeed.I really appreciate your help! Towards the end, I have one more question for you: Why does OpenPose output keypoints in groups of three when recognizing 2D, and in groups of four when recognizing 3D? I'm not quite clear on this. @foxtierney @xiangyann

**Comment by xiangyann** [comment]
> > 
> 
> > > @foxtierney I don't think we'd ever updated the Release build, so it shouldn't be having a build with hand detection...
> > 
> > 
> > That's true... The built version has not yet been updated... Good catch! I just did that.
> > @kekekou I have just rebuilt the project (and realized that there were .dlls that needed to be included) Please download the [latest release](https://github.com/foxtierney/RealSense2OpenPose3D/releases/tag/1.1) folder and try again. Thank you for your patience.
> 
> Sorry for the inconvenience. I've been busy with my coursework recently, but after downloading the new release, I was able to succeed.I really appreciate your help! Towards the end, I have one more question for you: Why does OpenPose output keypoints in groups of three when recognizing 2D, and in groups of four when recognizing 3D? I'm not quite clear on this. @foxtierney @xiangyann

The three points in 2D corresponds to:
x coordinate, y coordinate, confidence value
while in 3D it will correspond to:
x coordinate, y coordinate, z coordinate, confidence value.

**Comment by foxtierney** [comment]
> after downloading the new release, I was able to succeed.I really appreciate your help!

Awesome! I'm glad to hear that. I think that settles everything in this thread then. For those reading in the future, the release version 1.1 solved this issue.
